### ISSUE TITLE
Domain for app?

### ISSUE THREAD

**Issue by Saturate** [rfit/Oko#33]
Would be nice with a rf sub domain. This way people will know they are at the right place. However it's not super important but we need to know who controls the domains?

https://oko.roskilde-festival.dk
https://oko-staging.roskilde-festival.dk

What do you think, @skoleb ?

**Comment by skoleb** [comment]
I look into it. Regarding circleCI we have another site "Resources", with a simple setup:
https://github.com/rfit/portal/blob/master/.circleci/config.yml

**Comment by skoleb** [comment]
Email has been sent requesting RF domains. Setup on firebase can be found here:
https://firebase.google.com/docs/hosting/custom-domain?authuser=1&fbclid=IwAR2N4XT0431-OgdUzo5Xmq-C4_IVEp0XpOZcAxJZiCtJVBEgSGIF4_zeUR8

**Comment by Saturate** [comment]
https://oko.roskilde-festival.dk/
https://oko-staging.roskilde-festival.dk/

Are live! Great, we can close this.
